# Generated by Django 5.2 on 2026-04-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial_intake'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='intakerecord',
            new_name='intake_inta_tenant__8a0cff_idx',
            old_name='intake_inta_tenant__idx',
        ),
    ]
