# Generated by Django 5.2 on 2026-03-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_order_user_subscription_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['order'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planlar'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Abonelik', 'verbose_name_plural': 'Abonelikler'},
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.plan'),
        ),
    ]
