# Generated by Django 5.2 on 2026-03-28 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_plan_limits_and_flags(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    paid = (
        Plan.objects.filter(is_active=True)
        .exclude(slug="ucretsiz")
        .order_by("order", "pk")
    )
    rows = list(paid[:2])
    if len(rows) >= 1:
        p = rows[0]
        p.tryon_limit = 10
        p.wardrobe_limit = 50
        p.look_limit = 30
        p.editor_limit = 30
        p.style_session_limit = 30
        p.has_ai_stylist = True
        p.has_advanced_editor = True
        p.has_social_sharing = True
        p.save(
            update_fields=[
                "tryon_limit",
                "wardrobe_limit",
                "look_limit",
                "editor_limit",
                "style_session_limit",
                "has_ai_stylist",
                "has_advanced_editor",
                "has_social_sharing",
            ]
        )
    if len(rows) >= 2:
        p = rows[1]
        p.tryon_limit = 0
        p.wardrobe_limit = 0
        p.look_limit = 0
        p.editor_limit = 0
        p.style_session_limit = 0
        p.has_ai_stylist = True
        p.has_advanced_editor = True
        p.has_social_sharing = True
        p.has_priority_support = True
        p.has_hq_export = True
        p.is_popular = True
        p.save(
            update_fields=[
                "tryon_limit",
                "wardrobe_limit",
                "look_limit",
                "editor_limit",
                "style_session_limit",
                "has_ai_stylist",
                "has_advanced_editor",
                "has_social_sharing",
                "has_priority_support",
                "has_hq_export",
                "is_popular",
            ]
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_display_names_and_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='editor_limit',
            field=models.PositiveIntegerField(default=5, help_text='0 = sınırsız', verbose_name='Aylık editör kullanımı'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_advanced_editor',
            field=models.BooleanField(default=False, verbose_name='Gelişmiş editör'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_ai_stylist',
            field=models.BooleanField(default=False, verbose_name='AI stilist'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_hq_export',
            field=models.BooleanField(default=False, verbose_name='Yüksek kalite dışa aktarım'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_priority_support',
            field=models.BooleanField(default=False, verbose_name='Öncelikli destek'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_social_sharing',
            field=models.BooleanField(default=False, verbose_name='Sosyal paylaşım'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popüler plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='look_limit',
            field=models.PositiveIntegerField(default=5, help_text='0 = sınırsız', verbose_name='Maksimum görünüm (look)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='style_session_limit',
            field=models.PositiveIntegerField(default=5, help_text='0 = sınırsız', verbose_name='Aylık stil danışmanlığı'),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Deneme süresi (gün)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tryon_limit',
            field=models.PositiveIntegerField(default=3, help_text='0 = sınırsız', verbose_name='Aylık sanal deneme limiti'),
        ),
        migrations.AddField(
            model_name='plan',
            name='wardrobe_limit',
            field=models.PositiveIntegerField(default=10, help_text='0 = sınırsız', verbose_name='Maksimum gardırop öğesi'),
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_type', models.CharField(choices=[('tryon', 'Sanal Deneme'), ('editor', 'Görsel Editör'), ('style_session', 'Stil Danışmanlığı'), ('look_create', 'Görünüm Oluşturma')], max_length=50)),
                ('month', models.DateField(help_text='Ayın ilk günü (örn. 2024-01-01)')),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Özellik Kullanımı',
                'verbose_name_plural': 'Özellik Kullanımları',
                'indexes': [models.Index(fields=['user', 'month'], name='subscriptio_user_id_e6de36_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'feature_type', 'month'), name='subscriptions_featureusage_user_feature_month_uniq')],
            },
        ),
        migrations.RunPython(seed_plan_limits_and_flags, noop_reverse),
    ]
