# Generated by Django 5.2 on 2026-04-07 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_multitenant_subscription_featureusage'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ai_credits_monthly',
            field=models.PositiveIntegerField(default=0, help_text='0 = bu planda harici AI kotası yok.', verbose_name='Aylık harici AI kredisi'),
        ),
        migrations.AddField(
            model_name='plan',
            name='external_ai_enabled',
            field=models.BooleanField(default=False, verbose_name='Harici AI (WearView / Zmo / Style3D)'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='ai_credits_reset_date',
            field=models.DateTimeField(blank=True, help_text='Boşsa ilk kullanımda ay başına göre atanır.', null=True, verbose_name='Harici AI kredi sıfırlama zamanı'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='ai_credits_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Kullanılan harici AI kredisi (dönem)'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['tenant', 'month'], name='subscriptio_tenant__6c987d_idx'),
        ),
    ]
