# Generated by Django 5.2 on 2026-04-07 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integrations', '0003_production_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquotalog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_logs', to='ai_integrations.aiprocessingtask'),
        ),
    ]
