# Generated by Django 5.2 on 2026-04-19 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integrations', '0004_nullable_quota_task'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprocessingtask',
            name='output_data',
            field=models.JSONField(blank=True, default=dict, help_text='Anahtarlar: submit (API gönderimi), api_trail (failover), last_failure (hata ayıklama), webhook (geri çağırma yükü).'),
        ),
        migrations.AlterField(
            model_name='aiprocessingtask',
            name='task_type',
            field=models.CharField(choices=[('tryon', 'Sanal deneme'), ('model_generation', 'Model üretimi'), ('texture_creation', 'Doku / kumaş üretimi'), ('background_removal', 'Arka plan kaldırma'), ('pose_transfer', 'Poz aktarımı'), ('garment_3d', '3D kıyafet'), ('pattern_generation', 'Desen üretimi'), ('fabric_simulation', 'Kumaş simülasyonu')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='aiprocessingtask',
            index=models.Index(fields=['tenant', 'external_task_id'], name='ai_integrat_tenant__0d535f_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingtask',
            index=models.Index(fields=['provider', 'external_task_id'], name='ai_integrat_provide_3e4705_idx'),
        ),
    ]
