# Generated by Django 5.2 on 2026-04-07 21:17

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wearview', 'WearView'), ('zmo', 'Zmo.ai'), ('style3d', 'Style3D')], db_index=True, max_length=32, unique=True)),
                ('api_key_encrypted', django_cryptography.fields.encrypt(models.TextField(blank=True))),
                ('base_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, help_text='Dakika başına en fazla istek (önbellek penceresi).')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Sağlayıcıya özel uç yolları ve ek parametreler.')),
            ],
            options={
                'verbose_name': 'AI sağlayıcı',
                'verbose_name_plural': 'AI sağlayıcılar',
            },
        ),
        migrations.CreateModel(
            name='AIProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('tryon', 'Sanal deneme'), ('model_generation', 'Model üretimi'), ('texture_creation', 'Doku / kumaş üretimi')], max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Kuyrukta'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal')], db_index=True, default='queued', max_length=32)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('external_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_processing_tasks', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='ai_integrations.aiprovider')),
            ],
            options={
                'verbose_name': 'AI işlem kaydı',
                'verbose_name_plural': 'AI işlem kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuotaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_logs', to='ai_integrations.aiprocessingtask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_quota_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI kota günlüğü',
                'verbose_name_plural': 'AI kota günlükleri',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='aiprocessingtask',
            index=models.Index(fields=['tenant', 'status'], name='ai_integrat_tenant__f0cce6_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingtask',
            index=models.Index(fields=['tenant', 'created_at'], name='ai_integrat_tenant__f3f017_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquotalog',
            index=models.Index(fields=['tenant', 'timestamp'], name='ai_integrat_tenant__b93934_idx'),
        ),
    ]
