# Generated by Django 5.2 on 2026-04-07 21:28

import django.db.models.deletion
import django_cryptography.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_ai_quota_log_amounts(apps, schema_editor):
    AIQuotaLog = apps.get_model("ai_integrations", "AIQuotaLog")
    for row in AIQuotaLog.objects.all().iterator():
        if row.note == "refund":
            row.transaction_type = "refund"
            row.credits_amount = int(row.credits_used or 0)
        else:
            row.transaction_type = "usage"
            row.credits_amount = -int(row.credits_used or 0)
        row.save(update_fields=["transaction_type", "credits_amount"])


def noop_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integrations', '0002_seed_ai_providers'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiquotalog',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI kota günlüğü', 'verbose_name_plural': 'AI kota günlükleri'},
        ),
        migrations.RemoveIndex(
            model_name='aiquotalog',
            name='ai_integrat_tenant__b93934_idx',
        ),
        migrations.RemoveField(
            model_name='aiquotalog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='aiprocessingtask',
            name='estimated_credits',
            field=models.PositiveIntegerField(default=0, help_text='İş kuyruğa alınırken hesaplanan değer.', verbose_name='Tahmini kredi'),
        ),
        migrations.AddField(
            model_name='aiprocessingtask',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='1 en yüksek (ileride kuyruk sıralaması için).', verbose_name='Öncelik'),
        ),
        migrations.AddField(
            model_name='aiprocessingtask',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiprocessingtask',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Webhook alındı'),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='cost_per_request',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Fiyatlandırma / raporlama için; kota hâlâ plandan.', max_digits=10, verbose_name='Birim maliyet (bilgi)'),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='display_name',
            field=models.CharField(blank=True, help_text='Admin listelerinde gösterilir; boşsa name kullanılır.', max_length=120, verbose_name='Görünen ad'),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='fallback_provider',
            field=models.ForeignKey(blank=True, help_text='Birincil sağlayıcı kullanılamazsa denenecek yedek.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='ai_integrations.aiprovider'),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='supports_async',
            field=models.BooleanField(default=True, verbose_name='Asenkron iş destekler'),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='supports_sync',
            field=models.BooleanField(default=True, verbose_name='Senkron yanıt destekler'),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='webhook_secret_encrypted',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Webhook HMAC doğrulaması (boşsa ortam değişkeni kullanılır).')),
        ),
        migrations.AddField(
            model_name='aiquotalog',
            name='balance_after',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sonraki kullanılan kota'),
        ),
        migrations.AddField(
            model_name='aiquotalog',
            name='balance_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Önceki kullanılan kota'),
        ),
        migrations.AddField(
            model_name='aiquotalog',
            name='credits_amount',
            field=models.IntegerField(default=0, help_text='Kullanım için negatif, iade için pozitif.', verbose_name='İşaretli miktar'),
        ),
        migrations.AddField(
            model_name='aiquotalog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiquotalog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiquotalog',
            name='transaction_type',
            field=models.CharField(choices=[('usage', 'Kullanım'), ('refund', 'İade'), ('adjustment', 'Düzeltme'), ('bonus', 'Bonus')], db_index=True, default='usage', max_length=32),
        ),
        migrations.AlterField(
            model_name='aiprocessingtask',
            name='task_type',
            field=models.CharField(choices=[('tryon', 'Sanal deneme'), ('model_generation', 'Model üretimi'), ('texture_creation', 'Doku / kumaş üretimi'), ('background_removal', 'Arka plan kaldırma'), ('pose_transfer', 'Poz aktarımı'), ('garment_3d', '3D kıyafet')], max_length=64),
        ),
        migrations.AlterField(
            model_name='aiquotalog',
            name='credits_used',
            field=models.PositiveIntegerField(default=0, help_text='Eski alan: mutlak miktar (geriye dönük uyumluluk).'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingtask',
            index=models.Index(fields=['status', 'created_at'], name='ai_integrat_status_f6383d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquotalog',
            index=models.Index(fields=['tenant', 'created_at'], name='ai_integrat_tenant__4f33c0_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquotalog',
            index=models.Index(fields=['tenant', 'transaction_type'], name='ai_integrat_tenant__491bf4_idx'),
        ),
        migrations.RunPython(backfill_ai_quota_log_amounts, noop_backfill),
    ]
