# Generated by Django 5.2 on 2026-03-19 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0001_initial'),
        ('wardrobe', '0002_alter_garment_options_alter_garmentcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tryonsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Try-On Oturumu', 'verbose_name_plural': 'Try-On Oturumları'},
        ),
        migrations.AddField(
            model_name='tryonsession',
            name='canvas_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tryonsession',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tryonsession',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tryonsession',
            name='garment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_sessions', to='wardrobe.garment'),
        ),
        migrations.AlterField(
            model_name='tryonsession',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='tryon/output/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tryonsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tryonsession',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='tryon/input/%Y/%m/'),
        ),
    ]
