# Generated by Django 5.2 on 2026-04-19 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dressifyeuser_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressifyeuser',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Kayıtta post_save ile kişisel tenant atanır; çoklu kiracı üyeliği için genişletilebilir.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='tenants.tenant'),
        ),
    ]
