# Generated by Django 5.2 on 2026-03-21 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('creator', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='looks/%Y/%m/')),
                ('components_json', models.JSONField(default=dict)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Görünüm Paketi',
                'verbose_name_plural': 'Görünüm Paketleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('review_text', models.TextField(blank=True)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='looks.lookpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Görünüm Puanı',
                'verbose_name_plural': 'Görünüm Puanları',
                'unique_together': {('look', 'user')},
            },
        ),
    ]
