# Generated by Django 5.2 on 2026-03-21 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('example_images', models.JSONField(default=list)),
                ('prompt_template', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Avatar Stili',
                'verbose_name_plural': 'Avatar Stilleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='avatar/backgrounds/%Y/%m/')),
                ('location_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Arka Plan Şablonu',
                'verbose_name_plural': 'Arka Plan Şablonları',
            },
        ),
        migrations.CreateModel(
            name='AvatarSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_selfie', models.ImageField(upload_to='avatar/input/%Y/%m/')),
                ('result_images', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_sessions', to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avatar.avatarstyle')),
            ],
            options={
                'verbose_name': 'Avatar Oturumu',
                'verbose_name_plural': 'Avatar Oturumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
