# Generated by Django 5.2 on 2026-04-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarsession',
            name='output_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='avatarsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='avatarsession',
            name='input_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/input/%Y/%m/'),
        ),
    ]
