# Generated by Django 5.2 on 2026-03-19 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='body_shape',
            field=models.CharField(blank=True, choices=[('hourglass', 'Kum Saati'), ('pear', 'Armut'), ('apple', 'Elma'), ('rectangle', 'Dikdörtgen'), ('inverted_triangle', 'Ters Üçgen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bust',
            field=models.PositiveSmallIntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hips',
            field=models.PositiveSmallIntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_styles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_tone',
            field=models.CharField(blank=True, choices=[('light', 'Açık'), ('medium', 'Orta'), ('olive', 'Zeytinyağı'), ('dark', 'Koyu'), ('deep', 'Derin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='waist',
            field=models.PositiveSmallIntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='kg', null=True),
        ),
    ]
