# Generated by Django 5.2 on 2026-04-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_dressifye_subscription_and_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dressifye_marketing_tier',
            field=models.CharField(blank=True, choices=[('', '—'), ('starter', 'Starter'), ('elite', 'Elite'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='', max_length=20),
        ),
    ]
