# Generated by Django 5.2.12 on 2026-04-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#c9a84c', max_length=7)),
                ('favicon', models.URLField(blank=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('ai_prompt_prefix', models.TextField(blank=True)),
                ('ai_temperature', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenantlar',
                'ordering': ['name'],
            },
        ),
    ]
