# Generated by Django 5.2.12 on 2026-04-04 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='data_type',
            field=models.CharField(choices=[('hair', 'Saç/Sağlık'), ('style_basic', 'Temel Stil'), ('fashion', 'Tam Moda'), ('master', 'Merkez/Hepsi')], db_index=True, default='master', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sync_to_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_sources', to='tenant.tenant'),
        ),
        migrations.CreateModel(
            name='CrossTenantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_external_id', models.CharField(db_index=True, max_length=255)),
                ('data_type', models.CharField(db_index=True, max_length=50)),
                ('data_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('source_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_data', to='tenant.tenant')),
                ('target_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_data', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Çapraz tenant verisi',
                'verbose_name_plural': 'Çapraz tenant verileri',
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['user_external_id', 'data_type'], name='tenant_cros_user_ex_66afd3_idx')],
            },
        ),
    ]
