# Generated by Django 5.2 on 2026-04-21 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookApplySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='looks/sessions/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata')], default='pending', max_length=20)),
                ('output_data', models.JSONField(default=dict)),
                ('look', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='looks.lookpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Look Uygulama Oturumu',
                'verbose_name_plural': 'Look Uygulama Oturumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
