# Generated by Django 5.2 on 2026-03-21 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_options_alter_usersubscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tryon_count', models.PositiveIntegerField(default=0)),
                ('editor_count', models.PositiveIntegerField(default=0)),
                ('wardrobe_count', models.PositiveIntegerField(default=0)),
                ('reset_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanım Kotası',
                'verbose_name_plural': 'Kullanım Kotaları',
            },
        ),
    ]
