# Generated by Django 5.2 on 2026-04-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_ai_integrations_and_plan_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='avatar_limit',
            field=models.PositiveIntegerField(default=2, help_text='0 = sınırsız', verbose_name='Aylık avatar oluşturma limiti'),
        ),
        migrations.AddField(
            model_name='plan',
            name='hair_limit',
            field=models.PositiveIntegerField(default=3, help_text='0 = sınırsız', verbose_name='Aylık saç değiştirme limiti'),
        ),
        migrations.AddField(
            model_name='plan',
            name='look_apply_limit',
            field=models.PositiveIntegerField(default=5, help_text='0 = sınırsız', verbose_name='Aylık look uygulama limiti'),
        ),
        migrations.AddField(
            model_name='plan',
            name='makeup_limit',
            field=models.PositiveIntegerField(default=3, help_text='0 = sınırsız', verbose_name='Aylık makyaj deneme limiti'),
        ),
        migrations.AlterField(
            model_name='featureusage',
            name='feature_type',
            field=models.CharField(choices=[('tryon', 'Sanal Deneme'), ('editor', 'Görsel Editör'), ('style_session', 'Stil Danışmanlığı'), ('look_create', 'Görünüm Oluşturma'), ('makeup', 'Makyaj Deneme'), ('hair', 'Saç Değiştirme'), ('avatar', 'Avatar Oluşturma'), ('look_apply', 'Look Uygulama')], max_length=50),
        ),
    ]
