# Generated by Django 5.2.12 on 2026-04-04 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehlr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressifyeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dressifye kullanıcısı',
                'verbose_name_plural': 'Dressifye kullanıcıları',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='DressifyeGarment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('size', models.CharField(blank=True, max_length=32)),
                ('image_url', models.URLField(blank=True, max_length=2048)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='mehlr.dressifyeuser')),
            ],
            options={
                'verbose_name': 'Dressifye kıyafet',
                'verbose_name_plural': 'Dressifye kıyafetleri',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('style_notes', models.TextField(blank=True)),
                ('color_palette', models.JSONField(blank=True, default=list)),
                ('synced_to_dressifye', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_recommendations', to='mehlr.conversation')),
                ('garments', models.ManyToManyField(blank=True, related_name='outfit_recommendations', to='mehlr.dressifyegarment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_recommendations', to='mehlr.dressifyeuser')),
            ],
            options={
                'verbose_name': 'Kombin önerisi',
                'verbose_name_plural': 'Kombin önerileri',
                'ordering': ['-created_at'],
            },
        ),
    ]
