# Generated by Django 5.2.12 on 2026-04-04 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehlr', '0002_dressifye_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitRecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('liked', 'Beğenildi'), ('disliked', 'Beğenilmedi')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='mehlr.outfitrecommendation')),
            ],
            options={
                'verbose_name': 'Kombin geri bildirimi',
                'verbose_name_plural': 'Kombin geri bildirimleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
