# Generated by Django 5.2 on 2026-03-21 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('tryon', 'Try-On'), ('stylist', 'Stil Asistanı'), ('wardrobe_add', 'Gardırop Ekleme'), ('editor', 'Editör'), ('makeup', 'Makyaj'), ('hair', 'Saç'), ('avatar', 'Avatar')], max_length=30)),
                ('metadata', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanım Olayı',
                'verbose_name_plural': 'Kullanım Olayları',
                'ordering': ['-created_at'],
            },
        ),
    ]
