# Generated by Django 5.2 on 2026-03-19 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bust', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waist', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hips', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('body_shape', models.CharField(blank=True, choices=[('hourglass', 'Kum saati'), ('pear', 'Armut'), ('apple', 'Elma'), ('rectangle', 'Dikdörtgen'), ('inverted_triangle', 'Ters üçgen')], max_length=30)),
                ('skin_tone', models.CharField(blank=True, max_length=50)),
                ('preferred_styles', models.JSONField(default=list)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
