# Generated by Django 5.2 on 2026-03-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='measurement_privacy',
            field=models.CharField(choices=[('private', 'Gizli'), ('anon', 'Anonim'), ('public', 'Herkese açık')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_privacy',
            field=models.CharField(choices=[('private', 'Gizli'), ('anon', 'Anonim'), ('public', 'Herkese açık')], default='private', max_length=10),
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shoulder_width', models.PositiveSmallIntegerField(blank=True, help_text='Omuz genişliği (cm)', null=True)),
                ('arm_length', models.PositiveSmallIntegerField(blank=True, help_text='Kol uzunluğu (cm)', null=True)),
                ('leg_length', models.PositiveSmallIntegerField(blank=True, help_text='İç bacak uzunluğu (cm)', null=True)),
                ('neck', models.PositiveSmallIntegerField(blank=True, help_text='Boyun çevresi (cm)', null=True)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_measurement', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Vücut Ölçümü',
                'verbose_name_plural': 'Vücut Ölçümleri',
            },
        ),
        migrations.CreateModel(
            name='SizePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size_system', models.CharField(choices=[('tr', 'Türkiye'), ('eu', 'Avrupa (EU)'), ('us', 'ABD (US)'), ('uk', 'İngiltere (UK)')], default='tr', max_length=5)),
                ('top_size', models.CharField(blank=True, max_length=20)),
                ('bottom_size', models.CharField(blank=True, max_length=20)),
                ('shoe_size', models.CharField(blank=True, max_length=10)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_preference', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Beden Tercihi',
                'verbose_name_plural': 'Beden Tercihleri',
            },
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='avatars/generated/%Y/%m/')),
                ('body_type', models.CharField(blank=True, max_length=30)),
                ('skin_tone', models.CharField(blank=True, max_length=20)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_avatar', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Kullanıcı Avatarı',
                'verbose_name_plural': 'Kullanıcı Avatarları',
            },
        ),
    ]
