# Generated by Django 5.2 on 2026-04-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_add_city_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dressifye_display_title',
            field=models.CharField(blank=True, default='', help_text='Örn. Princess Duygu — vitrin / rapor başlığı', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dressifye_marketing_tier',
            field=models.CharField(blank=True, choices=[('', '—'), ('elite', 'Elite'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='feature_voice_ai',
            field=models.BooleanField(default=False, verbose_name='Sesli AI asistan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='feature_white_label_reports',
            field=models.BooleanField(default=False, verbose_name='White-label raporlar'),
        ),
    ]
