# Generated by Django 5.2 on 2026-03-19 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kıyafet', 'verbose_name_plural': 'Kıyafetler'},
        ),
        migrations.AlterModelOptions(
            name='garmentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AddField(
            model_name='garment',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='season',
            field=models.CharField(choices=[('all', 'Her Mevsim'), ('spring', 'İlkbahar/Yaz'), ('fall', 'Sonbahar/Kış')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='garmentcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garments', to='wardrobe.garmentcategory'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='image',
            field=models.ImageField(upload_to='garments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='garment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to=settings.AUTH_USER_MODEL),
        ),
    ]
