# Generated by Django 5.2 on 2026-03-21 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_alter_garment_options_alter_garmentcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('garments', models.ManyToManyField(blank=True, related_name='outfits', to='wardrobe.garment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kombin',
                'verbose_name_plural': 'Kombinler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardrobeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_value', models.CharField(blank=True, max_length=100)),
                ('ai_generated', models.BooleanField(default=False)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_tags', to='wardrobe.garment')),
            ],
            options={
                'verbose_name': 'Gardırop Etiketi',
                'verbose_name_plural': 'Gardırop Etiketleri',
            },
        ),
        migrations.CreateModel(
            name='WearLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('weather', models.CharField(blank=True, max_length=50)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wearlog/%Y/%m/')),
                ('garment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wear_logs', to='wardrobe.garment')),
                ('outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wear_logs', to='wardrobe.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wear_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giyim Kaydı',
                'verbose_name_plural': 'Giyim Kayıtları',
                'ordering': ['-date'],
            },
        ),
    ]
