# Generated by Django 5.2 on 2026-03-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_garment_subcategory_outfit_wardrobetag_wearlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garmentcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AddField(
            model_name='garment',
            name='color_hex',
            field=models.CharField(blank=True, help_text='#RRGGBB', max_length=7),
        ),
        migrations.AddField(
            model_name='garment',
            name='is_ai_processed',
            field=models.BooleanField(default=False, help_text='Arka plan temizlendi mi?'),
        ),
        migrations.AddField(
            model_name='garment',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='garment',
            name='last_worn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='garment',
            name='pattern',
            field=models.CharField(blank=True, choices=[('duz', 'Düz'), ('cizgili', 'Çizgili'), ('puanli', 'Puanlı'), ('cicekli', 'Çiçekli'), ('ekose', 'Ekose')], max_length=20),
        ),
        migrations.AddField(
            model_name='garment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='purchase_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='garment',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='store_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='garment',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='garments/thumbs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='garment',
            name='times_worn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garmentcategory',
            name='color',
            field=models.CharField(default='#C9A84C', max_length=7),
        ),
        migrations.AddField(
            model_name='garmentcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='garment',
            name='season',
            field=models.CharField(choices=[('4mevsim', '4 Mevsim'), ('yaz', 'Yaz'), ('kis', 'Kış'), ('bahar', 'Bahar'), ('sonbahar', 'Sonbahar'), ('all', 'Her Mevsim'), ('spring', 'İlkbahar/Yaz'), ('fall', 'Sonbahar/Kış')], default='4mevsim', max_length=20),
        ),
        migrations.AlterField(
            model_name='garment',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('ust', 'Üst Giyim'), ('alt', 'Alt Giyim'), ('dis', 'Dış Giyim'), ('ayakkabi', 'Ayakkabı'), ('aksesuar', 'Aksesuar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='garmentcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji veya Lucide icon adı', max_length=50),
        ),
    ]
