# Generated by Django 5.2 on 2026-03-21 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='beauty/looks/%Y/%m/')),
                ('products_json', models.JSONField(default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('creator', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Makyaj Görünümü',
                'verbose_name_plural': 'Makyaj Görünümleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MakeupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.CharField(choices=[('lipstick', 'Ruj'), ('eyeshadow', 'Far'), ('blush', 'Allık'), ('foundation', 'Fondöten'), ('eyeliner', 'Eyeliner'), ('mascara', 'Rimel'), ('brow', 'Kaş')], max_length=20)),
                ('color_hex', models.CharField(default='#000000', max_length=7)),
                ('opacity', models.FloatField(default=1.0)),
                ('brand', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Makyaj Ürünü',
                'verbose_name_plural': 'Makyaj Ürünleri',
            },
        ),
        migrations.CreateModel(
            name='MakeupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_image', models.ImageField(upload_to='beauty/input/%Y/%m/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='beauty/output/%Y/%m/')),
                ('products_json', models.JSONField(default=list)),
                ('applied_look', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty.makeuplook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Makyaj Oturumu',
                'verbose_name_plural': 'Makyaj Oturumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
