# Generated by Django 5.2 on 2026-04-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupsession',
            name='output_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='makeupsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='makeupsession',
            name='input_image',
            field=models.ImageField(blank=True, null=True, upload_to='beauty/input/%Y/%m/'),
        ),
    ]
