# Generated by Django 5.2 on 2026-03-21 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('adjustments_json', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Düzenleme Preseti',
                'verbose_name_plural': 'Düzenleme Presetleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_image', models.ImageField(upload_to='editor/original/%Y/%m/')),
                ('edited_image', models.ImageField(blank=True, null=True, upload_to='editor/edited/%Y/%m/')),
                ('edits_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Düzenleme Oturumu',
                'verbose_name_plural': 'Düzenleme Oturumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
