# Generated by Django 5.2 on 2026-04-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_alter_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(db_index=True, help_text='iyziReferenceCode veya içerik özeti', max_length=128, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Webhook olayı',
                'verbose_name_plural': 'Webhook olayları',
                'ordering': ['-created_at'],
            },
        ),
    ]
