# Generated by Django 5.2 on 2026-04-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_kind',
            field=models.CharField(choices=[('checkout', 'Tek seferlik CheckoutForm'), ('subscription_checkout', 'Abonelik CheckoutForm')], default='checkout', max_length=40),
        ),
    ]
