# Generated by Django 5.2 on 2026-03-19 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styling', '0001_initial'),
        ('wardrobe', '0002_alter_garment_options_alter_garmentcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylesession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stil Oturumu', 'verbose_name_plural': 'Stil Oturumları'},
        ),
        migrations.AddField(
            model_name='stylesession',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stylesession',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stylesession',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stylesession',
            name='suggested_outfit',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stylesession',
            name='user_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stylesession',
            name='garments_suggested',
            field=models.ManyToManyField(blank=True, related_name='style_sessions', to='wardrobe.garment'),
        ),
        migrations.AlterField(
            model_name='stylesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
