# Generated by Django 5.2 on 2026-03-21 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(max_length=7)),
                ('category', models.CharField(max_length=20)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='hair/colors/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Saç Rengi',
                'verbose_name_plural': 'Saç Renkleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HairStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hair/styles/%Y/%m/')),
                ('overlay_data', models.JSONField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Saç Stili',
                'verbose_name_plural': 'Saç Stilleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HairSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_image', models.ImageField(upload_to='hair/input/%Y/%m/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='hair/output/%Y/%m/')),
                ('applied_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hair.haircolor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hair_sessions', to=settings.AUTH_USER_MODEL)),
                ('applied_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hair.hairstyle')),
            ],
            options={
                'verbose_name': 'Saç Oturumu',
                'verbose_name_plural': 'Saç Oturumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
